table users {
  id interger [primary key, increment, not null]
  name varchar(100) [not null]
  email varchar(255) [not null, unique]
  password longtext [not null]
  created_at timestamp [not null]
  updated_at timestamp [not null]
}

table files {
  id integer [primary key, increment, not null]
  name varchar(255) [not null, unique]
  originName varchar(255) [not null]
  status varchar(10) [not null]
  created_at timestamp [not null]
  updated_at timestamp [not null]
}

table share_file {
  file_id integer [ref: - files.id]
  hash varchar(20) [not null, unique]
  name varchar(255) [ref: - files.name]
  created_at timestamp [not null]
  updated_at timestamp [not null]
  expires_in timestamp [null]
}